version: "3.7"

services:
  db:
    image: postgres:13
    restart: on-failure
    container_name: db
    environment:
      POSTGRES_USER: "aditya"
      POSTGRES_PASSWORD: "aditya1234"
      POSTGRES_DB: "stocks_warehouse"
    volumes:
      - ./db_setup:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"